A/A/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home'))
]

A/home/urls.py
from django.urls import path
from . import views


app_name='home'
urlpatterns = [
    path('',views.HomeView.as_view(),name ='home'),
    path('1/',views.Home2View.as_view(),),
    path('2/',views.Home3View.as_view(),),
    path('3/',views.Home4View.as_view(),),
    path('4/<int:year>/<str:name>/<str:owner>/',views.Home5View.as_view(),name='car_detail'),
    path('5/',views.Home6View.as_view(),name='car_create'),
    path('6/',views.Home7View.as_view(),),
    path('7/<int:pk>/',views.Home8View.as_view(),name='car_delete'),
    path('8/<int:pk>/',views.Home9View.as_view(),name='car_update'),
    path('accounts/login',views.AccountsLoginView.as_view(),name='login'),
    path('accounts/logout/',views.AccountsLogout.as_view(),name='logout'),
    path('api/',views.HomeApiView.as_view()),
    path('api/<int:pk>',views.SingleCarView.as_view()),
    path('api/delete/<str:name>/',views.CarDeleteView.as_view()),
    path('api/create/',views.CarCreateView.as_view()),
    path('api/update/<int:pk>/',views.CArUpdateView.as_view()),
    path('api/a/',views.CarListCreateView.as_view()),

]

A/home/models.py
from django.db import models

# Create your models here.


class Car(models.Model):
    name = models.CharField(max_length=100)
    owner = models.CharField(max_length=100)
    year = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.name

A/home/forms.py
from django import forms
from .models import  Car

class CarCreateForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = '__all__'

A/home/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView, RedirectView,DetailView ,CreateView,DeleteView,UpdateView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.contrib import messages
from .models import  Car
from .forms import CarCreateForm
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_view
from .serializers import CarSerializers
from rest_framework.generics import ListAPIView,RetrieveAPIView,DestroyAPIView,CreateAPIView,UpdateAPIView,ListCreateAPIView



class HomeView(View):
    def get(self,request):
        return render(request,'home/index.html')

    def options(self, request, *args, **kwargs):
        response = super().options(request,*args,**kwargs)
        response.headers['host'] = 'local-host'
        response.headers['user'] = request.user
        return response

class Home2View(TemplateView):
    template_name = 'home/index2.html'

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex['cars']=Car.objects.all()
        return contex

class Home3View(RedirectView):
    # url = 'http://google.com'
    pattern_name = 'home:home'
    query_string = False

    def get_redirect_url(self, *args, **kwargs):
        print('-'*90)
        print('processing your request ... ')
        return super().get_redirect_url(*args,**kwargs)

class Home4View(ListView):
    template_name = 'home/index2.html'
    # model = Car
    # queryset = Car.objects.filter(year__gte=2000)
    context_object_name = 'cars'
    ordering = '-year'
    # allow_empty = False

    def get_queryset(self):
        result = Car.objects.filter(year__gte=2023)
        return result

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex['name'] = 'mobin'
        return contex

class Home5View(DetailView):
    template_name = 'home/detail.html'
    model = Car
    # slug_field = 'name'
    # slug_url_kwarg = 'my_slug'

    def get_object(self, queryset=None):
        return Car.objects.get(
            year = self.kwargs['year'],
            name = self.kwargs['name'],
            owner = self.kwargs['owner'],
        )

class Home6View(FormView):
    template_name = 'home/create.html'
    form_class = CarCreateForm
    success_url = reverse_lazy('home:home')

    def form_valid(self, form):
        self._create_car(form.cleaned_data)
        messages.success(self.request,'create car successfully','success')
        return super().form_valid(form)


    def _create_car(self,data):
        Car.objects.create(name=data['name'],owner=data['owner'],year=data['year'])


class Home7View(CreateView):
    model = Car
    fields = ['name','year']
    template_name = 'home/create.html'
    success_url = reverse_lazy('home:home')

    def form_valid(self, form):
        car = form.save(commit=False)
        car.owner = self.request.user.username if self.request.user.username else 'nothing'
        car.save()
        messages.success(self.request,'create car successfully','success')
        return super().form_valid(form)

class Home8View(DeleteView):
    model = Car
    success_url = reverse_lazy('home:home')
    template_name = 'home/delete.html'

class Home9View(UpdateView):
    model = Car
    fields = ['name','year']
    success_url = reverse_lazy('home:home')
    template_name = 'home/update.html'

class AccountsLoginView(auth_view.LoginView):
    template_name = 'home/login.html'
    next_page = reverse_lazy('home:home')

class AccountsLogout(auth_view.LogoutView):
    next_page = reverse_lazy('home:home')

class HomeApiView(ListAPIView):
    serializer_class = CarSerializers
    queryset = Car.objects.all()

class SingleCarView(RetrieveAPIView):
    serializer_class =  CarSerializers
    queryset = Car.objects.all()
    # lookup_field = 'name'

class CarDeleteView(DestroyAPIView):
    serializer_class = CarSerializers
    queryset = Car.objects.all()
    lookup_field = 'name'

class CarCreateView(CreateAPIView):
    serializer_class = CarSerializers
    queryset = Car.objects.all()

class CArUpdateView(UpdateAPIView):
    serializer_class = CarSerializers
    queryset = Car.objects.all()

class CarListCreateView(ListCreateAPIView):
    serializer_class = CarSerializers
    queryset = Car.objects.all()

A/home/templates/home/create.html
{% extends "base.html" %}


{% block content %}

    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="create">
    </form>
{% endblock %}

A/home/templates/home/delete.html
{% extends "base.html" %}


{% block content %}

<form method="post">
    {% csrf_token %}
    <p>Are you delete this post {{ object }} ?</p>
    <input type="submit" value="yes">
</form>

{% endblock %}

A/home/templates/home/detail.html
{% extends "base.html" %}


{% block content %}
<p>{{ object.name }}</p>
<p>{{ object.owner }}</p>
<p>{{ object.year }}</p>
{% endblock %}

A/home/templates/home/index.html
{% extends "base.html" %}


{% block content %}

<p>Home</p>

{% endblock %}

A/home/templates/home/index2.html
{% extends "base.html" %}


{% block content %}

<h1>Home {{ name }}</h1>

{% for car in object_list %}
    <p><a href="{% url 'home:car_detail' car.year car.name car.owner %}">{{ car.name }}</a>
    <a href="{% url 'home:car_delete' car.id %}">Delete</a>
    <a href="{% url 'home:car_update' car.id %}">Update</a>
    </p>
{% endfor %}
{% endblock %}

A/home/templates/home/login.html
{% extends "base.html" %}


{% block content %}
<h3>Login page</h3>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form>

{% endblock %}

A/home/templates/home/update.html
{% extends "base.html" %}


{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}

A/templates/base.html
<!DOCTYPE html>
<html lang="en" >


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <style>
        .jumbotron{
            padding:20px;
            margin-bottom:20px;
            background-color:#e9ecef;
            }
    </style>
</head>
<body>
    {% include "inc/navbar.html" %}
    <div class="jumbotron">
    {% include "inc/messages.html" %}
    {% block content %}{% endblock content %}
    </div>
</body>
</html>

A/templates/inc/messages.html
{% if messages %}
{% for msg in messages %}
<p class="alert alert-{{ msg.tags }}">{{ msg }}<p>

{% endfor %}

{% endif %}

A/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark " data-bs-theme="dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Home</a>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Profile</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Bucket</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Logout</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"></a>
          </li>

          <li class="nav-item">
            <a class="nav-link " href="{% url 'home:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="#">Register</a>
          </li>

        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>